### ISSUE TITLE
problem accessing config.ini

### ISSUE THREAD

**Issue by chrismatheson** [timhaak/docker-sickbeard#10]
Hi,

I've done as much debugging as i can but I'm stuck with the following stack trace :(

I'm using docker-compose to orchestrate a few services (others are fine) but the python based services are both giving me this same problem.

I was originally mapping a value into `/data` but I've tried with a basic config containing no mappings and that does not help either.

any suggestions on what to try next would be greatly appreciated :D

```
couchpotato    | CouchPotato settings
couchpotato    | ====================
couchpotato    | 
couchpotato    |   User:       couchpotato
couchpotato    |   UID:        666
couchpotato    |   GID:        666
couchpotato    | 
couchpotato    |   Config:     /datadir/config.ini
couchpotato    | 
couchpotato    | Updating UID / GID... [DONE]
couchpotato    | Set permissions... [DONE]
couchpotato    | Starting CouchPotato...
couchpotato    | Traceback (most recent call last):
couchpotato    |   File "./CouchPotato.py", line 133, in <module>
couchpotato    |     l.run()
couchpotato    |   File "./CouchPotato.py", line 89, in run
couchpotato    |     runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
couchpotato    |   File "/couchpotato/couchpotato/runner.py", line 240, in runCouchPotato
couchpotato    |     Env.setting('api_key', value = api_key)
couchpotato    |   File "/couchpotato/couchpotato/environment.py", line 72, in setting
couchpotato    |     s.save()
couchpotato    |   File "/couchpotato/couchpotato/core/settings.py", line 172, in save
couchpotato    |     with open(self.file, 'wb') as configfile:
couchpotato    | IOError: [Errno 13] Permission denied: '/datadir/config.ini'
```

compose.yml

```
version: '2'
services:
  sickbeard:
     container_name: "sickbeard"
    image: sickbeard/sickbeard
#    volumes:
#      - "/tmp/blackhole:/blackhole"
#      - "/tmp/sb:/datadir"
#      - "/tmp/media/tv:/media"
    ports:
      - '8081:8081'
    restart: always
```
